---
all:
  hosts:
    kohastaging:
      ansible_host: 89.45.232.196
      ansible_user: apps
      environment_name: staging
      intranet_server_name: "koha-staging-intra.ub.gu.se"
      intranet_port: 443
      opac_server_name: "koha-staging.ub.gu.se"
      opac_port: 443
      https: true
      plack: true
      koha_home: "/home/{{ ansible_user }}/koha-staging/current"
      koha_repo_version: release-2022.02-20220310.1613
      koha_po_files_path: "/home/{{ ansible_user }}/koha-staging/shared/misc/translator/po"
      koha_instance_name: koha
      perl5lib_paths: "{{ koha_home }}/lib:{{ koha_home }}"
      koha_elasticsearch_server: "localhost:9200"
      koha_memcached_servers: "localhost:11211"
      koha_db_host: "localhost"
      koha_db_password: "{{ vault_koha_db_password }}"
      mariadb_root_password: "{{ vault_mariadb_root_password }}"
      gobi_report_mail_to: david.gustafsson@ub.gu.se,g.katalog@ub.gu.se
      gobi_error_mail_to: david.gustafsson@ub.gu.se,g.katalog@ub.gu.se,stefan.berndtsson@ub.gu.se
      koha_online_payment_portal_url: https://betala-staging.ub.gu.se/Koha/Payment
