---
all:
  hosts:
    kohastaging:
      ansible_host: 89.45.232.196
      ansible_user: apps
      koha_home: /home/apps/koha/current
      koha_instance_name: koha
      koha_db_password: "{{ vault_koha_db_password }}"
