- hosts: all
  become: true
  become_user: root
  vars_files:
    - docker/build/vars/shared.yml
    - vars/vault.yml # TODO: Move to group vars?
    - vars/gobi_defaults.yml
    - vars/fetchlibris_defaults.yml
    - vars/loadlibris_defaults.yml
    - vars/libris_oai_import_defaults.yml
    - vars/edifact_defaults.yml
    - vars/primo_export_defaults.yml
  tasks:
    # TODO: Bit of a hack
  - name: Set primo export data dir
    ansible.builtin.set_facts:
      primo_export_export_dir: "/var/lib/koha/primo/{{ koha_instance_name }}" # Referenced in env vars, needed for volume mount

  - name: Ensure export directories
    ansible.builtin.file:
      path: "{{ primo_export_export_dir }}"
      mode: 0755
      #owner: "{{ primo_export_user }}"
      #group: "{{ primo_export_user }}"
      state: directory

  - name: Deploy app
    include_role:
      name: ub-ansible-deploy

  - name: Ensure SIP-server configuration
    ansible.builtin.template:
      src: SIPconfig.xml.j2
      dest: "/etc/koha/sites/{{ koha_instance_name }}/SIPconfig.xml"

  # GUB-scripts
  - name: Write /usr/local/sbin/koha-database-backup.sh
    ansible.builtin.template:
      src: koha-database-backup.sh.j2
      dest: /usr/local/sbin/koha-database-backup.sh
      mode: 0544

  - name: Ensure log directory for koha-database-backup.sh
    ansible.builtin.file:
      path: "{{ koha_database_backup_log_dir }}"
      mode: 0755
      state: directory

  - name: Ensure data directory for koha-database-backup.sh
    ansible.builtin.file:
      path: "{{ koha_database_backup_data_dir }}"
      mode: 0755
      state: directory

  # Fetchlibris
  - name: Write fetchlibris.sh.conf
    template:
      src: fetchlibris.sh.conf.j2
      dest: "{{ fetchlibris_conf_file_path }}"

  # Loadlibris
  - name: Ensure bulkmarcimport.log exists with correct owner
    ansible.builtin.file:
      path: "{{ data_dirs['loadlibris_log'].path }}/bulkmarcimport.log"
      owner: "{{ koha_uid }}"
      group: "{{ koha_uid }}"
      state: touch

  - name: Write loadlibris.sh.conf
    template:
      src: loadlibris.sh.conf.j2
      dest: "{{ loadlibris_conf_file_path }}"

  # Libris oai import
  - name: Write export_nix.sh.conf
    template:
      src: export_nix.sh.conf.j2
      dest: "{{ libris_oai_import_conf_file_path }}"

  # Gobi
  - name: Ensure bulkmarcimport.log exists with correct owner
    ansible.builtin.file:
      path: "{{ data_dirs['gobi_log'].path }}/bulkmarcimport.log"
      owner: "{{ koha_uid }}"
      group: "{{ koha_uid }}"
      state: touch
    become: yes

  - name: Write loadgobi.sh.conf
    template:
      src: loadgobi.sh.conf.j2
      dest: "{{ loadgobi_conf_file_path }}"

  - name: Write log4perl.conf
    template:
      src: log4perl.conf.j2
      dest: "{{ gobi_log4perl_conf_file_path }}"

  # Edifact
  - name: Ensure vendor directories
    ansible.builtin.file:
      path: "{{ data_dirs['edifact_vendors'] }}/{{ item.0 }}/{{ item.1 }}"
      mode: 0755
      state: directory
      owner: "{{ koha_uid }}"
      group: "{{ koha_uid }}"
    loop: "{{ ['dawson', 'delbanco', 'adlibris', 'bokus'] | product(['archive', 'messages']) | list }}"
    become: yes

  - name: Write upload_edi.conf.yml
    template:
      src: upload_edi.conf.yml.j2
      dest: "{{ upload_edifact_conf_file_path }}"

  - name: Schedule edifact cron jobs
    ansible.builtin.cron:
      name: "upload-edifact-{{ item.0 }}"
      minute: "{{ item.1 }}"
      hour: "22"
      job: "cd \"{{ docker_directory_path }}\"; {{ docker_command }} exec {{ edifact_repo_path }}/upload_edi.pl \"{{ upload_edifact_conf_file_path }}\" {{ item.0 }} >> {{ data_dirs['edifact'] }}/upload_edi.log 2>&1"
      state: "{{ 'present' if edifact_cron_enabled else 'absent' }}"
      cron_file: 'edifact'
      user: root
    loop: "{{ ['dawson', 'delbanco', 'adlibris', 'bokus']|zip(['30', '32', '34', '36'])|list }}"
    become: yes

  # Primo export

  # TODO: This still needed?
#  - name: Create primo export user
#    ansible.builtin.user:
#      name: "{{ primo_export_user }}"
#    become: yes
#
#  - name: Add public key of drupal-deploy user to authorized_keys
#    ansible.builtin.authorized_key:
#      user: "{{ primo_export_user }}"
#      state: present
#      key: "{{ lookup('file', '{{ playbook_dir }}/files/primo_export_user_authorized_keys') }}"
#    become: yes

  - name: Ensure primo export directories
    ansible.builtin.file:
      path: "{{ primo_export_export_dir }}/{{ item }}"
      mode: 0755
      #owner: "{{ primo_export_user }}"
      #group: "{{ primo_export_user }}"
      state: directory
    loop:
      - full
      - updates
      - databases # Drupal databases primo export directory
    become: yes

  - name: Write config
    template:
      src: primo-export.config.j2
      dest: "{{ primo_export_config_file_path }}"

  - name: Schedule primo export cron job
    ansible.builtin.cron:
      name: "koha-primo-export"
      minute: "30"
      hour: "04,16"
      job: "cd \"{{ docker_directory_path }}\"; {{ docker_command }} exec {{ primo_export_repo_path }}/sync_records.sh \"{{ primo_export_config_file_path }}\"  > /dev/null 2>&1"
      state: present
      user: root
    become: yes
