- hosts: all
  become: true
  become_user: root
  vars_files:
    - docker/build/vars/shared.yml
    - vars/vault.yml # TODO: Move to group vars?
    - vars/gobi_defaults.yml
    - vars/fetchlibris_defaults.yml
    - vars/loadlibris_defaults.yml
    - vars/libris_oai_import_defaults.yml
  tasks:

  - name: Deploy app
    include_role:
      name: ub-ansible-deploy

  - name: Ensure SIP-server configuration
    ansible.builtin.template:
      src: SIPconfig.xml.j2
      dest: "/etc/koha/sites/{{ koha_instance_name }}/SIPconfig.xml"

  # GUB-scripts
  - name: Write /usr/local/sbin/koha-database-backup.sh
    ansible.builtin.template:
      src: koha-database-backup.sh.j2
      dest: /usr/local/sbin/koha-database-backup.sh
      mode: 0544

  - name: Ensure log directory for koha-database-backup.sh
    ansible.builtin.file:
      path: "{{ koha_database_backup_log_dir }}"
      mode: 0755
      state: directory

  - name: Ensure data directory for koha-database-backup.sh
    ansible.builtin.file:
      path: "{{ koha_database_backup_data_dir }}"
      mode: 0755
      state: directory

  # Fetchlibris
  - name: Write fetchlibris.sh.conf
    template:
      src: fetchlibris.sh.conf.j2
      dest: "{{ fetchlibris_conf_file_path }}"

  # Loadlibris
  - name: Ensure bulkmarcimport.log exists with correct owner
    ansible.builtin.file:
      path: "{{ data_dirs['loadlibris_log'].path }}/bulkmarcimport.log"
      owner: "{{ koha_uid }}"
      group: "{{ koha_uid }}"
      state: touch

  - name: Write loadlibris.sh.conf
    template:
      src: loadlibris.sh.conf.j2
      dest: "{{ loadlibris_conf_file_path }}"

  # Libris oai import
  - name: Write export_nix.sh.conf
    template:
      src: export_nix.sh.conf.j2
      dest: "{{ libris_oai_import_conf_file_path }}"

  # Gobi
  - name: Ensure bulkmarcimport.log exists with correct owner
    ansible.builtin.file:
      path: "{{ data_dirs['gobi_log'].path }}/bulkmarcimport.log"
      owner: "{{ koha_uid }}"
      group: "{{ koha_uid }}"
      state: touch
    become: yes

  - name: Set log4perl conf file path
    ansible.builtin.set_fact:
      gobi_log4perl_conf_file_path: "{{ data_dirs['gobi'].path }}/log4perl.conf"

  - name: Write loadgobi.sh.conf
    template:
      src: loadgobi.sh.conf.j2
      dest: "{{ loadgobi_conf_file_path }}"

  - name: Write log4perl.conf
    template:
      src: log4perl.conf.j2
      dest: "{{ gobi_log4perl_conf_file_path }}"
