- hosts: all
  become: true
  become_user: root
  vars_files:
  - docker/build/vars/shared.yml
  - vars/vault.yml # TODO: Move to group vars?
  tasks:
    # TODO: Bit of a hack
  - name: Set primo export data dir
    ansible.builtin.set_fact:
      primo_export_export_dir: "/var/lib/koha/primo/{{ koha_instance_name }}" # Referenced in env vars, needed for volume mount

  - name: Ensure export directories
    ansible.builtin.file:
      path: "{{ primo_export_export_dir }}"
      mode: 0755
      #owner: "{{ primo_export_user }}"
      #group: "{{ primo_export_user }}"
      state: directory

  # Temporary hack to ensure koha derecory, fix (by breaking out directory creation task from ansible deploY?
  - name: Ensure koha-directory
    ansible.builtin.file:
      path: "{{ data_dirs['koha'].path }}"
      state: directory

  # TODO: Owner koha_uid?
  - name: Ensure SIP-server configuration
    ansible.builtin.template:
      src: SIPconfig.xml.j2
      dest: "{{ data_dirs['koha'].path }}/SIPconfig.xml"

  - name: Deploy app
    include_role:
      name: ub-ansible-deploy

  # Database export
  - name: Write /usr/local/sbin/koha-database-backup.sh
    ansible.builtin.template:
      src: koha-database-backup.sh.j2
      dest: /usr/local/sbin/koha-database-backup.sh
      mode: 0544

  - name: Schedule database backup cron job
    ansible.builtin.cron:
      name: "database-export"
      hour: "23"
      minute: "00"
      job: "/usr/local/sbin/koha-database-backup.sh >> {{ data_dirs['database_backup_log'].path }}/backup.log 2>&1"
      state: "{{ 'present' if database_export_cron_enabled else 'absent' }}"
      cron_file: "database-export"
      user: root
    become: yes

  # Loadlibris
  - name: Ensure bulkmarcimport.log exists with correct owner
    ansible.builtin.file:
      path: "{{ data_dirs['loadlibris_log'].path }}/bulkmarcimport.log"
      owner: "{{ koha_uid }}"
      group: "{{ koha_uid }}"
      state: touch

  - name: Schedule loadlibris cron job
    ansible.builtin.cron:
      name: "loadlibris"
      hour: "05"
      minute: "00"
      job: 'cd "{{ docker_directory_path }}"; {{ docker_command }} exec {{ loadlibris_repo_path }}/loadlibris.sh'
      state: "{{ 'present' if loadlibris_cron_enabled else 'absent' }}"
      cron_file: "loadlibris"
      user: root
    become: yes

  # Libris oai import
  - name: Schedule libris oai import cron job
    ansible.builtin.cron:
      name: "libris-oai-import"
      hour: "*"
      minute: "*"
      job: "cd \"{{ docker_directory_path }}\"; {{ docker_command }} exec {{ libris_oai_import_repo_path }}/export_nix.sh >> {{ data_dirs['libris_oai_import_log'].path }}/libris_oai.log 2>&1)" 
      state: "{{ 'present' if libris_oai_import_cron_enabled else 'absent' }}"
      cron_file: "libris-oai-import"
      user: root
    become: yes

  # Papercut
  - name: Schedule cron job
    ansible.builtin.cron:
      name: "papercut"
      minute: "*/5"
      job: "{{ cd \"{{ docker_directory_path }}\"; {{ docker_command }} exec papercut_repo_path }}/run_updated_borrowers.sh >> {{ data_dirs['papercut'].path }}/run_updated_borrowers.log 2>&1"
      state: "{{ 'present' if papercut_cron_enabled else 'absent' }}"
      cron_file: "papercut"
      user: root
    become: yes

  # Gobi
  - name: Ensure bulkmarcimport.log exists with correct owner
    ansible.builtin.file:
      path: "{{ data_dirs['gobi_import_log'].path }}/bulkmarcimport.log"
      owner: "{{ koha_uid }}"
      group: "{{ koha_uid }}"
      state: touch
    become: yes

  - name: Schedule gobi cron job
    ansible.builtin.cron:
      name: "gobi-import"
      hour: "23"
      minute: "30"
      job: "cd \"{{ docker_directory_path }}\"; {{ docker_command }} exec {{ gobi_import_repo_path }}/loadgobi.sh > /dev/null 2>&1"
      state: "{{ 'present' if gobi_import_cron_enabled else 'absent' }}"
      cron_file: "gobi-import"
      user: root
    become: yes

  # Edifact
  - name: Ensure vendor directories
    ansible.builtin.file:
      path: "{{ data_dirs['edifact_vendors'] }}/{{ item.0 }}/{{ item.1 }}"
      mode: 0755
      state: directory
      owner: "{{ koha_uid }}"
      group: "{{ koha_uid }}"
    loop: "{{ ['dawson', 'delbanco', 'adlibris', 'bokus'] | product(['archive', 'messages']) | list }}"
    become: yes

  - name: Schedule edifact cron jobs
    ansible.builtin.cron:
      name: "upload-edifact-{{ item.0 }}"
      minute: "{{ item.1 }}"
      hour: "22"
      job: "cd \"{{ docker_directory_path }}\"; {{ docker_command }} exec {{ edifact_repo_path }}/upload_edi.pl \"{{ upload_edifact_conf_file_path }}\" {{ item.0 }} >> {{ data_dirs['edifact'] }}/upload_edi.log 2>&1"
      state: "{{ 'present' if edifact_cron_enabled else 'absent' }}"
      cron_file: 'edifact'
      user: root
    loop: "{{ ['dawson', 'delbanco', 'adlibris', 'bokus']|zip(['30', '32', '34', '36'])|list }}"
    become: yes

  # Print notice
  - name: Schedule print notice cron job
    ansible.builtin.cron:
      name: "print-notice"
      minute: "00"
      hour: "08"
      job: "{{ cd \"{{ docker_directory_path }}\"; {{ docker_command }} exec print_notice_repo_path }}/send_all.sh >> {{ data_dirs['print_notice_log'].path }}/log/sendall.log 2>&1"
      state: present
      cron_file: "print-notice"
      user: root
    become: yes

  # Primo export
  # TODO: This still needed?
#  - name: Create primo export user
#    ansible.builtin.user:
#      name: "{{ primo_export_user }}"
#    become: yes
#
#  - name: Add public key of drupal-deploy user to authorized_keys
#    ansible.builtin.authorized_key:
#      user: "{{ primo_export_user }}"
#      state: present
#      key: "{{ lookup('file', '{{ playbook_dir }}/files/primo_export_user_authorized_keys') }}"
#    become: yes

  - name: Ensure primo export directories
    ansible.builtin.file:
      path: "{{ primo_export_export_dir }}/{{ item }}"
      mode: 0755
      #owner: "{{ primo_export_user }}"
      #group: "{{ primo_export_user }}"
      state: directory
    loop:
      - full
      - updates
      - databases # Drupal databases primo export directory
    become: yes

  - name: Write primo export config
    template:
      src: primo-export.config.j2
      dest: "{{ primo_export_config_file_path }}"

  - name: Schedule primo export cron job
    ansible.builtin.cron:
      name: "koha-primo-export"
      minute: "30"
      hour: "04,16"
      job: "cd \"{{ docker_directory_path }}\"; {{ docker_command }} exec {{ primo_export_repo_path }}/sync_records.sh \"{{ primo_export_config_file_path }}\"  > /dev/null 2>&1"
      state: present
      user: root
    become: yes
