version: '3.5'

services:
  koha-devbox:
    image: "devbox:1"
    ports:
      - "127.0.0.1:7100:80"
      - "127.0.0.1:7101:8080"
    cap_add:
     - SYS_NICE
     - DAC_READ_SEARCH
  mariadb:
    image: "mariadb:1"
    environment:
      MARIADB_ROOT_PASSWORD: root_password
      MARIADB_USER: koha_koha
      MARIADB_PASSWORD: password
      MARIADB_DATABASE: koha_koha
  elasticsearch:
    image: "elasticsearch:1"
    environment:
      - xpack.security.enabled=false
      - "discovery.type=single-node"
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      
  memcached:
    image: "memcached:1.6"
