---
- hosts: all
  vars_files:
    - vars/vault.yml
    - vars/defaults.yml
    - vars/gobi_defaults.yml
  tasks:
    - name: Ensure required directories
      ansible.builtin.file:
        path: "{{ gobi_data_dir }}/{{ item }}"
        mode: 0755
        state: directory
      become: yes
      loop:
        - bulkmarcimport_err
        - bulkmarcimport_in
        - adjustgobi_in
        - done
        - fetchgobi_done
        - log

    - name: Install Perl dependecies
      community.general.cpanm:
        name: "{{ item }}"
      become: yes
      loop:
        - Email::MIME
        - Email::Sender::Simple
        - IO::All
        - Params::ValidationCompiler

    - name: Ensure bulkmarcimport.log exists with correct owner
      ansible.builtin.file:
        path: "{{ gobi_data_dir }}/log/bulkmarcimport.log"
        owner: "{{ koha_user }}"
        group: "{{ koha_user }}"
        state: touch
      become: yes

    - name: Checkout repo
      ansible.builtin.git:
        repo: https://github.com/ub-digit/koha-gobi-import.git
        dest: "{{ gobi_home }}"
        version: "{{ gobi_version }}"

    - name: Write gobi.sh.conf
      template:
        src: gobi.sh.conf.j2
        dest: "{{ gobi_home }}/gobi.sh.conf"

    - name: Write log4perl.conf
      template:
        src: log4perl.conf.j2
        dest: "{{ gobi_home }}/log4perl.conf"

    - name: Schedule cron job
      ansible.builtin.cron:
        name: "koha-gobi-import"
        minute: "30"
        hour: "23"
        job: "{{ gobi_home }}/loadgobi.sh > /dev/null 2>&1"
        state: present
        user: root
      become: yes
