---
- hosts: all
  vars_files:
    - vars/defaults.yml
    - vars/koha_db_import.yml
    - vars/vault.yml
  become: true
  become_user: root
  tasks:
    - name: Drop current database
      community.mysql.mysql_db:
        name: "koha_{{ koha_instance_name }}"
        config_file: /etc/mysql/koha-common.cnf #??
        state: absent

    - name: Create dump data directory
      ansible.builtin.file:
        path: "{{ koha_db_import_data_dir }}"
        state: directory

    - name: Copy stashed database dump to remote host
      ansible.builtin.copy:
        src: "{{ playbook_dir }}/data/kohadump.sql.gz"
        dest: "{{ koha_db_import_data_dir }}/"

    - name: Import database
      community.mysql.mysql_db:
        name: "koha_{{ koha_instance_name }}"
        config_file: /etc/mysql/koha-common.cnf #??
        target: "{{ koha_db_import_data_dir }}/kohadump.sql.gz"
        state: import

    - name: Remove remote dump
      ansible.builtin.file:
        path: "{{ koha_db_import_data_dir }}/kohadump.sql.gz"
        state: absent
