---
- hosts: all
  vars_files:
    - vars/defaults.yml
    - vars/vault.yml
  become: true
  become_user: root
  tasks:
    - name: Checkout Koha repo
      ansible.builtin.git:
        repo: "{{ koha_repo_url }}"
        dest: "{{ koha_repo_path }}"
        version: "{{ koha_repo_version }}"

    # TODO: replace shell with command?
    - name: Install troublesome Perl modules (with failing tests)
      community.general.cpanm:
        name: "{{ item }}"
        notest: True
      loop:
        - Mojolicious::Plugin::OpenAPI
        - JSON::Validator
        - JSON::Validator::OpenAPI::Mojolicious
        - Cache::Memcached::Fast::Safe

    - name: Install dependecies not included in cpanfile
      community.general.cpanm:
        name: "{{ item }}"
      loop:
        - Alien::Tidyp
        - Switch # koha-plugin-format-facet dependency
        - LWP::Simple::Post # koha-plugin-get-print-data dependency
        - DBD::Pg # GUB postgres reports

  # - name: Install Koha perl dependencies
  #    ansible.builtin.shell: "cd {{ koha_home }} && cpanm --installdeps ."
    - name: Install Koha perl dependencies
      community.general.cpanm:
        from_path: "{{ koha_repo_path }}"
        installdeps: yes