---
- hosts: all
  vars_files:
    - vars/defaults.yml
    - vars/koha_db_fetch.yml
    - vars/vault.yml
  become: true
  become_user: root
  tasks:

    - name: Create dump directory
      ansible.builtin.file:
        path: "{{ koha_db_fetch_data_dir }}"
        state: directory

    - name: Dump database
      community.mysql.mysql_db:
        config_file: /etc/mysql/koha-common.cnf
        single_transaction: yes
        login_user: root # This can probably be omitted
        name: "koha_{{ koha_instance_name }}"
        state: dump
        target: "{{ koha_db_fetch_data_dir }}/kohadump.sql.gz"

    - name: Fetch database dump
      ansible.builtin.fetch:
        src: "{{ koha_db_fetch_data_dir }}/kohadump.sql.gz"
        dest: "{{ playbook_dir }}/data/"
        flat: yes

    - name: Remove remote dump
      ansible.builtin.file:
        path: "{{ koha_db_fetch_data_dir }}/kohadump.sql.gz"
        state: absent
