---
- hosts: all
  vars_files:
    - vars/fetchlibris_defaults.yml # Implicit dependecy. Perhaps not ideal, but makes "in" directory editable in one place
    - vars/loadlibris_defaults.yml
  tasks:
    - name: Ensure required directories
      ansible.builtin.file:
        path: "{{ loadlibris_data_dir }}/{{ item }}"
        mode: 0755
        state: directory
      become: yes
      loop:
        - in
        - in_archive
        - done
        - err
        - log

    - name: Ensure bulkmarcimport.log exists with correct owner
      ansible.builtin.file:
        path: "{{ loadlibris_data_dir }}/log/bulkmarcimport.log"
        owner: "{{ koha_user }}"
        group: "{{ koha_user }}"
        state: touch

    - name: Checkout repo
      ansible.builtin.git:
        repo: https://github.com/ub-digit/loadlibris.git
        dest: "{{ loadlibris_home }}"
        version: "{{ loadlibris_version }}"

    - name: Write loadlibris.sh.conf
      template:
        src: loadlibris.sh.conf.j2
        dest: "{{ loadlibris_home }}/loadlibris.sh.conf"

    - name: Schedule cron job
      ansible.builtin.cron:
        name: "koha-loadlibris"
        minute: "00"
        hour: "05"
        job: "{{ loadlibris_home }}/loadlibris.sh"
        state: present
        user: root
      become: yes
