---
- hosts: all
  vars:
    pip_install_packages:
      - name: PyMySQL
  vars_files:
    - vars/defaults.yml
    - vars/vault.yml
  roles:
    - geerlingguy.pip
  become: true
  become_user: root
  tasks:

    - name: Install gnupg
      apt:
        name: gnupg2
        state: present
        update_cache: yes

    - name: Add official Koha repository (key)
      ansible.builtin.apt_key:
        url: http://debian.koha-community.org/koha/gpg.asc
        state: present

    - name: Add official Koha repository (repo)
      ansible.builtin.apt_repository:
        repo: deb [trusted=yes] http://debian.koha-community.org/koha dev main
        update_cache: yes
        state: present

    - name: Install required packages
      apt:
        name: ['curl',
               'ntp',
               'emacs-nox',
               'vim', # vim-nox?
               'byobu',
               'htop',
               'tree',
               'libstring-similarity-perl', #??
               'apt-transport-https',
               'cpanminus',
               'libmariadb-dev-compat',
               'dh-make-perl',
               'git',
               'git-email',
               'libdata-printer-perl',
               'mlocate',
               'perltidy',
               'libstrictures-perl',
               # Koha-common dependencies as listed by `apt-cache depends koha-common`
               'debconf',
               'libalgorithm-checkdigits-perl',
               'libanyevent-http-perl',
               'libanyevent-perl',
               'libarchive-extract-perl',
               'libarchive-zip-perl',
               'libarray-utils-perl',
               'libauthen-cas-client-perl',
               'libbiblio-endnotestyle-perl',
               'libbusiness-isbn-perl',
               'libbusiness-issn-perl',
               'libbytes-random-secure-perl',
               'python3-apt', # Warning in ansible-role-pip
               'python3-mysqldb', # Required for ansible mysql collection
               'libpq-dev', # Required for DBD::Pg
               'libnet-z3950-zoom-perl',
               #'libcache-memcached-fast-safe-perl',
#               'libcache-memcached-perl',
#               'libcgi-compile-perl',
#               'libcgi-emulate-psgi-perl',
#               'libcgi-pm-perl',
#               'libcgi-session-driver-memcached-perl',
#               'libcgi-session-perl',
#               'libcgi-session-serialize-yaml-perl',
#               'libclass-accessor-perl',
#               'libclass-factory-util-perl',
#               'libclass-inspector-perl',
#               'libclone-perl',
#               'libcrypt-eksblowfish-perl',
#               'libdata-ical-perl',
#               'libdate-calc-perl',
#               'libdate-manip-perl',
#               'libdatetime-event-ical-perl',
#               'libdatetime-format-ical-perl',
#               'libdatetime-format-mysql-perl',
#               'libdatetime-perl',
#               'libdatetime-timezone-perl',
#               'libdbd-mock-perl',
#               'libdbd-mysql-perl',
#               'libdbd-sqlite2-perl',
#               'libdbi-perl',
#               'libdbix-class-schema-loader-perl',
#               'libdbix-runsql-perl',
#               'libdevel-cover-perl',
#               'libdigest-sha-perl',
#               'libemail-date-perl',
#               'libemail-messageid-perl',
#               'libemail-sender-perl',
#               'libemail-stuffer-perl',
#               'libemail-valid-perl',
#               'libexception-class-perl',
#               'libfile-slurp-perl',
#               'libfont-ttf-perl',
#               'libgd-barcode-perl',
#               'libgd-perl',
#               'libgraphics-magick-perl',
#               'libgravatar-url-perl',
#               'libhtml-format-perl',
#               'libhtml-parser-perl',
#               'libhtml-scrubber-perl',
#               'libhttp-cookies-perl',
#               'libhttp-message-perl',
#               'libhttp-oai-perl',
#               'libintl-perl',
#               'libjson-perl',
#               'libjson-validator-perl',
#               'liblibrary-callnumber-lc-perl',
#               'liblingua-ispell-perl',
#               'liblingua-stem-perl',
#               'liblingua-stem-snowball-perl',
#               'liblist-moreutils-perl',
#               'liblocale-codes-perl',
#               'liblocale-currency-format-perl',
#               'liblocale-po-perl',
#               'liblog-log4perl-perl',
#               'libwww-perl',
#               'libio-socket-ssl-perl',
#               'libmarc-charset-perl',
#               'libmarc-file-mij-perl',
#               'libmarc-record-perl',
#               'libmarc-xml-perl',
#               'libmime-lite-perl',
#               'libmodern-perl-perl',
#               'libmodule-bundled-files-perl',
#               'libmodule-cpanfile-perl',
#               'libmodule-load-conditional-perl',
#               'libmodule-pluggable-perl',
#               'libmojolicious-perl',
#               'libmojolicious-plugin-openapi-perl',
#               'libmoo-perl',
#               'libnet-cidr-perl',
#               'libnet-ldap-perl',
#               'libnet-netmask-perl',
#               'libnet-oauth2-authorizationserver-perl',
#               'libnet-server-perl',
#               'libnet-sftp-foreign-perl',
#               'libnet-stomp-perl',
#               'libnet-z3950-simpleserver-perl',
#               'libnet-z3950-zoom-perl',
#               'libnumber-format-perl',
#               'libopenoffice-oodoc-perl',
#               'libparallel-forkmanager-perl',
#               'libpdf-api2-perl',
#               'libpdf-fromhtml-perl',
#               'libpdf-reuse-barcode-perl',
#               'libpdf-reuse-perl',
#               'libpdf-table-perl',
#               'libplack-middleware-logwarn-perl',
#               'libplack-middleware-reverseproxy-perl',
#               'libreadonly-perl',
#               'libscalar-list-utils-perl',
#               'libschedule-at-perl',
#               'libsearch-elasticsearch-perl',
#               'libsereal-decoder-perl',
#               'libsereal-encoder-perl',
#               'libsms-send-perl',
#               'libstring-random-perl',
#               'libsys-cpu-perl',
#               'libtemplate-perl',
#               'libtemplate-plugin-gettext-perl',
#               'libtemplate-plugin-htmltotext-perl',
#               'libtemplate-plugin-json-escape-perl',
#               'libtemplate-plugin-stash-perl',
#               'libtest-deep-perl',
#               'libtest-exception-perl',
#               'libtest-mockmodule-perl',
#               'libtest-mockobject-perl',
#               'libtest-mocktime-perl',
#               'libtest-simple-perl',
#               'libtest-strict-perl',
#               'libtest-warn-perl',
#               'libtest-www-mechanize-perl',
#               'libtest-yaml-valid-perl',
#               'libtext-bidi-perl',
#               'libtext-csv-encoded-perl',
#               'libtext-csv-perl',
#               'libtext-csv-xs-perl',
#               'libtext-iconv-perl',
#               'libtext-pdf-perl',
#               'libtext-unidecode-perl',
#               'libtime-fake-perl',
#               'libtry-tiny-perl',
#               'libuniversal-can-perl',
#               'libuniversal-require-perl',
#               'liburi-perl',
#               'libuuid-perl',
#               'libwebservice-ils-perl',
#               'libwww-csrf-perl',
#               'libwww-perl',
#               'libxml-dumper-perl',
#               'libxml-libxml-perl',
#               'libxml-libxslt-perl',
#               'libxml-rss-perl',
#               'libxml-sax-perl',
#               'libxml-sax-writer-perl',
#               'libxml-simple-perl',
#               'libxml-writer-perl',
#               'libyaml-perl',
#               'libyaml-syck-perl',
               'gettext',
               'xsltproc',
               'docbook-xsl',
               'fonts-dejavu',
               'libxml2-utils',
               'bash-completion',
               'libtest-simple-perl',
               'apache2',
               'libapache2-mpm-itk',
               'at',
               'daemon',
               'debconf',
               'memcached',
               'perl-doc',
               'pwgen',
               'rabbitmq-server',
               'starman',
               'sudo',
               'unzip',
               'xmlstarlet',
               'yaz',
               'libyaz-dev',
               'pkg-config',
               'uuid-dev',
               'libgdome2-dev', #For XML::LibXSLT, might be dependecy of libgdome2 that makes it compile?
               'libfribidi-dev',
               'libgd-dev'
               ]
        state: latest
        force: no
        update_cache: yes
