- import_playbook: server-setup.yml
- import_playbook: elasticsearch.yml
- import_playbook: koha-setup.yml
- import_playbook: koha-config.yml
- import_playbook: mariadb.yml
- import_playbook: koha-instance-setup.yml
- import_playbook: exim-setup.yml
- import_playbook: printers-setup.yml
- import_playbook: koha-set-environment-preferences.yml
