---
- hosts: all
  vars_files:
    - vars/vault.yml
    - vars/defaults.yml
    - vars/edifact_defaults.yml
  tasks:
    - name: Install required packages
      apt:
        name: ftp
        state: latest
        update_cache: yes
      become: yes

    - name: Ensure data directory
      ansible.builtin.file:
        path: "{{ edifact_data_dir }}"
        mode: 0755
        owner: "koha-{{ koha_instance_name }}"
        group: "koha-{{ koha_instance_name }}"
        state: directory
      become: yes

    - name: Ensure vendor directories
      ansible.builtin.file:
        path: "{{ edifact_data_dir }}/vendors/{{ item.0 }}/{{ item.1 }}"
        mode: 0755
        state: directory
        owner: "koha-{{ koha_instance_name }}"
        group: "koha-{{ koha_instance_name }}"
      loop: "{{ ['Dawson', 'Delbanco', 'Adlibris', 'Bokus']|product(['archive', 'messages'])|list }}"
      become: yes

    - name: Checkout repo
      ansible.builtin.git:
        repo: https://github.com/ub-digit/koha-edifact.git
        dest: "{{ edifact_home }}"
        version: "{{ edifact_version }}"

    - name: Write upload_edi.conf.yml
      template:
        src: upload_edi.conf.yml.j2
        dest: "{{ edifact_home }}/upload_edi.conf.yml"

    - name: Schedule cron jobs
      ansible.builtin.cron:
        name: "koha-edifact-{{ item.0 }}"
        minute: "{{ item.1 }}"
        hour: "22"
        job: "{{ edifact_home }}/upload_edi.pl {{ item.0 }} >> {{ edifact_data_dir }}/upload_edi.log 2>&1"
        state: "{{ 'present' if edifact_cron_enabled else 'absent' }}"
        user: root
      loop: "{{ ['Dawson', 'Delbanco', 'Adlibris', 'Bokus']|zip(['30', '32', '34', '36'])|list }}"
      become: yes
