---
all:
  hosts:
    kohadevbox:
      ansible_host: localhost
      ansible_user: apps
      ansible_connection: local
      environment_name: devbox
      intranet_server_name: "localhost"
      intranet_port: 8080
      opac_server_name: "localhost"
      opac_port: 80
      https: false
      plack: false
      sip: false
      koha_home: "/home/{{ ansible_user }}/koha-repo"
      koha_repo_version: "release-2024.02-20240223.0839"
      koha_po_files_path: "/home/{{ ansible_user }}/koha-repo/misc/translator/po"
      koha_instance_name: koha
      koha_elasticsearch_server: "elasticsearch:9200"
      koha_memcached_servers: "memcached:11211"
      koha_db_host: "mariadb"
      koha_db_password: "{{ vault_koha_db_password }}"
      mariadb_root_password: "{{ vault_mariadb_root_password }}"
      koha_ipac_api_key: "ipac-api-key"
      get_print_data_api_key: "print-data-api-key"
      koha_mojilicious_secret_passphrase: "verysecret"
      gobi_report_mail_to: david.gustafsson@ub.gu.se,g.katalog@ub.gu.se
      gobi_error_mail_to: david.gustafsson@ub.gu.se,g.katalog@ub.gu.se,stefan.berndtsson@ub.gu.se
      koha_online_payment_portal_url: https://betala-staging.ub.gu.se/Koha/Payment
      pip_install_packages:
        - name: PyMySQL
      koha_data_dir: /mnt
      mariadb_data_dir: /mnt/mariadb
      elasticsearch_data_dir: /mnt/elasticsearch
      # Mail settings
      smtp_host: 127.0.0.1
      smtp_port: 1025
      smtp_username: ''
      smtp_password: ''
      smtp_ssl_mode: disabled
      koha_database_backup_cron_enabled: false
      gub_edifact_cron_enabled: false
      edifact_cron_enabled: false
      papercut_cron_enabled: false
      qa_repo: https://gitlab.com/koha-community/qa-test-tools.git
      qa_home: "/home/{{ ansible_user }}/qa-test-tools"
