---
all:
  hosts:
    kohadevbox:
      ansible_host: localhost
      ansible_user: apps
      ansible_connection: local
      environment_name: devbox
      intranet_server_name: "localhost"
      intranet_port: 8080
      opac_server_name: "localhost"
      opac_port: 80
      https: false
      plack: false
      sip: false
      koha_home: "/home/{{ ansible_user }}/koha-repo"
      koha_repo_version: "release-2022.02-20220310.1613"
      koha_po_files_path: "/home/{{ ansible_user }}/koha-repo/misc/translator/po"
      koha_instance_name: koha
      perl5lib_paths: "{{ koha_home }}/lib:{{ koha_home }}"
      koha_elasticsearch_server: "elasticsearch:9200"
      koha_memcached_servers: "memcached:11211"
      koha_db_host: "mariadb"
      koha_db_password: "{{ vault_koha_db_password }}"
      mariadb_root_password: "{{ vault_mariadb_root_password }}"
      gobi_report_mail_to: david.gustafsson@ub.gu.se,g.katalog@ub.gu.se
      gobi_error_mail_to: david.gustafsson@ub.gu.se,g.katalog@ub.gu.se,stefan.berndtsson@ub.gu.se
      koha_online_payment_portal_url: https://betala-staging.ub.gu.se/Koha/Payment
      pip_install_packages:
        - name: PyMySQL
