---
docker_git_repo_url: https://github.com/ub-digit/koha-ansible.git
docker_git_revision: ub-ansible-deploy
docker_directory: './docker' # Default is './docker'
app_name: koha # TODO: Needed?
ansible_python_interpreter: /usr/bin/python3

# Koha/apache
intranet_port: 443
opac_port: 443
https: true
plack: true
sip: true

koha_bcrypt_settings: "vault TODO"

# GUB custom koha-conf.xml options
koha_online_payments: 1
koha_online_payment_exclude_patron_categories: BA|BE|BF|BK|BL|BM|BN|BU|EI|TN|TJ|PE
koha_online_payment_info_url_en: https://www.ub.gu.se/en/borrow-and-log-in/borrowing-from-the-library
koha_online_payment_info_url_sv: https://www.ub.gu.se/sv/lana-och-logga-in/lana-pa-biblioteket

koha_ipac_api_key: "{{ vault_koha_ipac_api_key }}"
get_print_data_api_key: "{{ vault_get_print_data_api_key }}"
koha_mojilicious_secret_passphrase: "{{ vault_koha_mojilicious_secret_passphrase }}"

# koha_readonly_db_user_password: "{{ vault_koha_readonly_db_user_password }}"

# Mail settings
smtp_host: 127.0.0.1
smtp_port: 1025
smtp_username: ''
smtp_password: ''
smtp_ssl_mode: disabled

# Cron
database_backup_cron_enabled: false
loadlibris_cron_enabled: false
libris_oai_import_cron_enabled: false 
gobi_import_cron_enabled: false
gub_edifact_cron_enabled: false
edifact_cron_enabled: false
papercut_cron_enabled: true
print_notice_cron_enabled: true
primo_export_cron_enabled: true

koha_dir_defaults: &koha_dir_defaults
  mode: '0755'
  owner: "{{ koha_uid }}"
  group: "{{ koha_uid }}"
  pull: false
  push: false

# TODO: Data dirs for mounting of uploads (and more?)

data_dir: /data
koha_uid: 1000

data_dirs:
  mariadb:
    path: "{{ data_dir }}/mariadb-data"
    owner: 999
    group: 999
    mode: '0750'
    pull: false
    push: false
  postgres:
    path: "{{ data_dir }}/postgres-data"
    owner: 999
    group: 999
    mode: '0750'
    pull: false
    push: false
  elasticsearch:
    path: "{{ data_dir }}/elasticsearch-data"
    owner: 1000
    group: 1000
    mode: '0750'
    pull: true
    push: true
  database_backup:
    path: "{{ data_dir }}/database-backup"
    owner: root
    group: root
    mode: '0750'
    pull: false
    push: false
  koha:
    <<: *koha_dir_defaults
    path: "{{ data_dir }}/koha"
  edifact:
    <<: *koha_dir_defaults
    path: "{{ data_dir }}/edifact"
  papercut:
    <<: *koha_dir_defaults
    path: "{{ data_dir }}/papercut"
  edifact_vendors:
    <<: *koha_dir_defaults
    path: "{{ data_dir }}/edifact/vendors"
  fetchlibris:
    <<: *koha_dir_defaults
    path: "{{ data_dir }}/fetchlibris"
  fetchlibris_begun:
    <<: *koha_dir_defaults
    path: "{{ data_dir }}/fetchlibris/begun"
  fetchlibris_done:
    <<: *koha_dir_defaults
    path: "{{ data_dir }}/fetchlibris/done"
  fetchlibris_log:
    <<: *koha_dir_defaults
    path: "{{ data_dir }}/fetchlibris/log"
  loadlibris:
    <<: *koha_dir_defaults
    path: "{{ data_dir }}/loadlibris"
  loadlibris_in:
    <<: *koha_dir_defaults
    path: "{{ data_dir }}/loadlibris/in"
  loadlibris_in_archive:
    <<: *koha_dir_defaults
    path: "{{ data_dir }}/loadlibris/in_archive"
  loadlibris_done:
    <<: *koha_dir_defaults
    path: "{{ data_dir }}/loadlibris/done"
  loadlibris_err:
    <<: *koha_dir_defaults
    path: "{{ data_dir }}/loadlibris/err"
  loadlibris_log:
    <<: *koha_dir_defaults
    path: "{{ data_dir }}/loadlibris/log"
  libris_oai_import:
    <<: *koha_dir_defaults
    path: "{{ data_dir }}/libris-oai-import"
  libris_oai_import_download:
    <<: *koha_dir_defaults
    path: "{{ data_dir }}/libris-oai-import/download"
  libris_oai_import_archive:
    <<: *koha_dir_defaults
    path: "{{ data_dir }}/libris-oai-import/archive"
  libris_oai_import_log:
    <<: *koha_dir_defaults
    path: "{{ data_dir }}/libris-oai-import/log"
  print_notice:
    <<: *koha_dir_defaults
    path: "{{ data_dir }}/print-notice"
  print_notice_log:
    <<: *koha_dir_defaults
    path: "{{ data_dir }}/print-notice/log"
  gobi_import:
    <<: *koha_dir_defaults
    path: "{{ data_dir }}/gobi-import"
  gobi_import_bulkmarc_in:
    <<: *koha_dir_defaults
    path: "{{ data_dir }}/gobi-import/bulkmarcimport_in"
  gobi_import_bulkmarc_err:
    <<: *koha_dir_defaults
    path: "{{ data_dir }}/gobi-import/bulkmarcimport_err"
  gobi_import_adjustgobi_import_in:
    <<: *koha_dir_defaults
    path: "{{ data_dir }}/gobi-import/adjustgobi_import_in"
  gobi_import_fetchgobi_import_done:
    <<: *koha_dir_defaults
    path: "{{ data_dir }}/gobi-import/gobifetchgobi_import_done"
  gobi_import_done:
    <<: *koha_dir_defaults
    path: "{{ data_dir }}/gobi-import/done"
  gobi_import_log:
    <<: *koha_dir_defaults
    path: "{{ data_dir }}/gobi-import/log"
  primo_export:
    <<: *koha_dir_defaults
    path: "{{ data_dir }}/primo-export"
