---
all:
  hosts:
    kohaproduction:
      ansible_host: 130.241.35.139
      ansible_user: apps
      environment_name: production
      intranet_server_name: "koha-intra.ub.gu.se"
      intranet_port: 443
      opac_server_name: "koha.ub.gu.se"
      opac_port: 443
      https: true
      plack: true
      koha_home: "/home/{{ ansible_user }}/koha-production/current"
      koha_repo_version: release-2022.02-20220310.1613
      koha_po_files_path: "/home/{{ ansible_user }}/koha-production/shared/misc/translator/po"
      koha_instance_name: koha
      perl5lib_paths: "{{ koha_home }}/lib:{{ koha_home }}"
      koha_elasticsearch_server: "localhost:9200"
      koha_memcached_servers: "localhost:11211"
      koha_db_host: "localhost"
      koha_db_password: "{{ vault_koha_db_password }}"
      mariadb_root_password: "{{ vault_mariadb_root_password }}"
      gobi_report_mail_to: david.gustafsson@ub.gu.se,g.katalog@ub.gu.se
      gobi_error_mail_to: david.gustafsson@ub.gu.se,g.katalog@ub.gu.se,stefan.berndtsson@ub.gu.se
      koha_online_payment_portal_url: https://betala-production.ub.gu.se/Koha/Payment
      # data dirs
      koha_database_backup_data_dir: /mnt/data/backup/koha-database-backup
      mariadb_data_dir: /mnt/database
      elasticsearch_data_dir: /mnt/data/elasticsearch
      koha_db_import_data_dir: /mnt/data/koha_db_import
      koha_db_fetch_data_dir: /mnt/data/koha_db_fetch
