---
all:
  hosts:
    kohaproduction:
      ansible_host: 130.241.35.151
      ansible_user: apps
      environment_name: production
      intranet_server_name: "koha-intra.ub.gu.se"
      intranet_port: 443
      opac_server_name: "koha.ub.gu.se"
      opac_port: 443
      https: true
      plack: true
      sip: true
      koha_home: "/home/{{ ansible_user }}/koha-production/current"
      koha_repo_version: release-2022.02-20220419.1118
      koha_instance_name: koha
      koha_elasticsearch_server: "localhost:9200"
      koha_memcached_servers: "localhost:11211"
      koha_db_host: "localhost"
      koha_db_password: "{{ vault_koha_db_password }}"
      mariadb_root_password: "{{ vault_mariadb_root_password }}"
      koha_ipac_api_key: "{{ vault_koha_ipac_api_key }}"
      get_print_data_api_key: "{{ vault_get_print_data_api_key }}"
      koha_mojilicious_secret_passphrase: "{{ vault_koha_mojilicious_secret_passphrase }}"
      gobi_report_mail_to: david.gustafsson@ub.gu.se,g.katalog@ub.gu.se
      gobi_error_mail_to: david.gustafsson@ub.gu.se,g.katalog@ub.gu.se,stefan.berndtsson@ub.gu.se
      koha_online_payment_portal_url: https://betala-production.ub.gu.se/Koha/Payment
      # data dirs
      koha_data_dir: /mnt/data
      mariadb_data_dir: /mnt/database/mariadb
      elasticsearch_data_dir: /mnt/database/elasticsearch
      # Mail settings
      smtp_host: 127.0.0.1
      smtp_port: 1025
      smtp_username: ''
      smtp_password: ''
      smtp_ssl_mode: disabled
