version: '3.5'
services:
  koha:
    volumes:
      - "${SIPCONFIG_HOST_FILE}:/etc/koha/sites/${KOHA_INSTANCE_NAME}/SIPconfig.xml"
      - "${EDIFACT_HOST_CONF_FILE}:/opt/koha-edifact/upload_edi.conf.yml" # Hard coded for now
      - "${DATABASE_BACKUP_HOST_DIR}:${DATABASE_BACKUP_DIR}"
      - "${EDIFACT_DATA_HOST_DIR}:${EDIFACT_DATA_DIR}"
      - "${PRINT_NOTICE_DATA_HOST_DIR}:${PRINT_NOTICE_DATA_DIR}"
      - "${FETCHLIBRIS_DATA_HOST_DIR}:${FETCHLIBRIS_DATA_DIR}"
      - "${LOADLIBRIS_DATA_HOST_DIR}:${LOADLIBRIS_DATA_DIR}"
      - "${LIBRIS_OAI_IMPORT_DATA_HOST_DIR}:${LIBRIS_OAI_IMPORT_DATA_DIR}"
      - "${PAPERCUT_DATA_HOST_DIR}:${PAPERCUT_DATA_DIR}"
      - "${GOBI_IMPORT_DATA_HOST_DIR}:${GOBI_IMPORT_DATA_DIR}"
      - "${PRIMO_EXPORT_DATA_HOST_DIR}:${PRIMO_EXPORT_DATA_DIR}"
      - "${PRIMO_EXPORT_EXPORT_HOST_DIR}:${PRIMO_EXPORT_EXPORT_DIR}"
      - "${KOHA_LOG_HOST_DIR}:/var/log/koha/${KOHA_INSTANCE_NAME}"
