version: '3.5'
services:
  koha:
    image: docker.ub.gu.se/koha-base:${GIT_REVISION}
    environment:
      KOHA_INSTANCE_NAME: "${KOHA_INSTANCE_NAME}"
      KOHA_USER: "${KOHA_USER}"
      KOHA_REPO_PATH: "${KOHA_REPO_PATH}"
      SCRIPTS_KOHA_SHELL_PATH: "/opt/koha-loadlibris/koha-shell" #TODO: avoid hard coding path?
      SMTP_HOST: "${SMTP_HOST}"
      SMTP_PORT: "${SMTP_PORT}"
      PLACK_MAX_REQUESTS: "${PLACK_MAX_REQUESTS}"
      PLACK_WORKERS: "${PLACK_WORKERS}"
      INFOBIP_API_KEY: "${INFOBIP_API_KEY}"
      INFOBIP_SENDER: "${INFOBIP_SENDER}"
      INFOBIP_BASEURL: "${INFOBIP_BASEURL}"
      TO_OVERRIDE: "${TO_OVERRIDE}"
      INFOBIP_SKIP_SEND: "${INFOBIP_SKIP_SEND}"
      EDIFACT_BASE_DIR: "${EDIFACT_BASE_DIR}"
      EDIFACT_EMAIL: "${EDIFACT_EMAIL}"
      PRINT_NOTICE_DATA_DIR: "${PRINT_NOTICE_DATA_DIR}"
      FETCHLIBRIS_DONE_DIR: "${FETCHLIBRIS_DONE_DIR}"
      FETCHLIBRIS_BEGUN_DIR: "${FETCHLIBRIS_BEGUN_DIR}"
      FETCHLIBRIS_LOG_DIR: "${FETCHLIBRIS_LOG_DIR}"
      FETCHLIBRIS_EMAIL: "${FETCHLIBRIS_EMAIL}"
      LOADLIBRIS_IN_DIR: "${LOADLIBRIS_IN_DIR}"
      LOADLIBRIS_IN_ARCHIVE_DIR: "${LOADLIBRIS_IN_ARCHIVE_DIR}"
      LOADLIBRIS_ERR_DIR: "${LOADLIBRIS_ERR_DIR}"
      LOADLIBRIS_LOG_DIR: "${LOADLIBRIS_LOG_DIR}"
      LOADLIBRIS_DONE_DIR: "${LOADLIBRIS_DONE_DIR}"
      LIBRIS_OAI_IMPORT_DATA_DIR: "${LIBRIS_OAI_IMPORT_DATA_DIR}"
      PRIMO_EXPORT_EXPORT_DIR: "/var/lib/koha/primo/${KOHA_INSTANCE_NAME}"
      PRIMO_EXPORT_DATA_DIR: "${PRIMO_EXPORT_DATA_DIR}"
      PRIMO_EXPORT_EXPORT_DIR: "${PRIMO_EXPORT_EXPORT_DIR}"
      GOBI_IMPORT_REPORT_MAIL_TO: "${GOBI_IMPORT_REPORT_MAIL_TO}"
      GOBI_IMPORT_ERROR_MAIL_TO: "${GOBI_IMPORT_ERROR_MAIL_TO}"
      GOBI_IMPORT_LOG_DIR: "${GOBI_IMPORT_LOG_DIR}"
      GOBI_IMPORT_LOG4PERL_CONF_FILE_PATH: "/opt/koha-gobi-import/log4perl.conf" # TODO: Relative path works?
    cap_add:
     - SYS_NICE
     - DAC_READ_SEARCH
    depends_on:
      - mariadb
      - elasticsearch
      - rabbitmq
  mariadb:
    image: mariadb:10.11-jammy
    environment:
      MARIADB_ROOT_PASSWORD: root_password
      MARIADB_USER: koha_koha
      MARIADB_PASSWORD: password
      MARIADB_DATABASE: koha_koha
    volumes:
      - ./mariadb-initdb.d:/docker-entrypoint-initdb.d:ro
      - "${MARIADB_DATA_HOST_DIR}:/var/lib/mysql"
  elasticsearch:
    image: docker.ub.gu.se/koha-elasticsearch:${ELASTICSEARCH_VERSION}
    environment:
      - xpack.security.enabled=false
      - "discovery.type=single-node"
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g" #TODO: Higher for production
    volumes:
      - "${ELASTICSEARCH_DATA_HOST_DIR}:/usr/share/elasticsearch/data"
  memcached:
    image: memcached:1.6
    command:
      - memcached
      - -m
      - 64m
  rabbitmq:
    image: docker.ub.gu.se/koha-rabbitmq:${RABBITMQ_VERSION}
