version: '3.5'
services:
  koha:
    volumes:
      - "${DATABASE_BACKUP_HOST_DIR}:${DATABASE_BACKUP_CONTAINER_DIR}"
      - "${EDIFACT_DATA_HOST_DIR}:${EDIFACT_DATA_CONTAINER_DIR}"
      - "${FETCHLIBRIS_DATA_HOST_DIR}:${FETCHLIBRIS_DATA_CONTAINER_DIR}"
      - "${LOADLIBRIS_DATA_HOST_DIR}:${LOADLIBRIS_DATA_CONTAINER_DIR}"
      - "${LOADLIBRIS_OAI_IMPORT_DATA_HOST_DIR}:${LOADLIBRIS_OAI_IMPORT_DATA_CONTAINER_DIR}"
      - "${GOBI_DATA_HOST_DIR}:${GOBI_DATA_CONTAINER_DIR}"
      - "${PRIMO_EXPORT_DATA_HOST_DIR}:${PRIMO_EXPORT_DATA_CONTAINER_DIR}"
