version: '3.5'
services:
  koha:
    env_file:
      - secrets.env
    image: docker.ub.gu.se/koha:${GIT_REVISION}
    environment:
      KOHA_INSTANCE_NAME: "${KOHA_INSTANCE_NAME}"
      KOHA_ENVIRONMENT: "${KOHA_ENVIRONMENT}"
      KOHA_USER: "${KOHA_USER}"
      KOHA_REPO_PATH: "${KOHA_REPO_PATH}"
      KOHA_PG_DATABASE: ${KOHA_PG_DATABASE}
      KOHA_PG_HOSTNAME: postgres
      KOHA_PG_PORT: 5432
      KOHA_PG_USER: ${KOHA_PG_USER}
      KOHA_PG_PASS: ${KOHA_PG_PASS}
      SCRIPTS_KOHA_SHELL_PATH: "/opt/koha-loadlibris/koha-shell" #TODO: avoid hard coding path?
      SMTP_HOST: "${SMTP_HOST}"
      SMTP_PORT: "${SMTP_PORT}"
      PLACK_MAX_REQUESTS: "${PLACK_MAX_REQUESTS}"
      PLACK_WORKERS: "${PLACK_WORKERS}"
      PLACK_ENVIRONMENT: "${PLACK_ENVIRONMENT}"
      INFOBIP_API_KEY: "${INFOBIP_API_KEY}"
      INFOBIP_SENDER: "${INFOBIP_SENDER}"
      INFOBIP_BASEURL: "${INFOBIP_BASEURL}"
      TO_OVERRIDE: "${TO_OVERRIDE}"
      INFOBIP_SKIP_SEND: "${INFOBIP_SKIP_SEND}"
      PRINT_NOTICE_DATA_DIR: "${PRINT_NOTICE_DATA_DIR}"
      FETCHLIBRIS_DONE_DIR: "${FETCHLIBRIS_DONE_DIR}"
      FETCHLIBRIS_BEGUN_DIR: "${FETCHLIBRIS_BEGUN_DIR}"
      FETCHLIBRIS_LOG_DIR: "${FETCHLIBRIS_LOG_DIR}"
      FETCHLIBRIS_EMAIL: "${FETCHLIBRIS_EMAIL}"
      LOADLIBRIS_IN_DIR: "${LOADLIBRIS_IN_DIR}"
      LOADLIBRIS_IN_ARCHIVE_DIR: "${LOADLIBRIS_IN_ARCHIVE_DIR}"
      LOADLIBRIS_ERR_DIR: "${LOADLIBRIS_ERR_DIR}"
      LOADLIBRIS_LOG_DIR: "${LOADLIBRIS_LOG_DIR}"
      LOADLIBRIS_DONE_DIR: "${LOADLIBRIS_DONE_DIR}"
      LIBRIS_OAI_IMPORT_DATA_DIR: "${LIBRIS_OAI_IMPORT_DATA_DIR}"
      PRIMO_EXPORT_DATA_DIR: "${PRIMO_EXPORT_DATA_DIR}"
      PRIMO_EXPORT_EXPORT_DIR: "${PRIMO_EXPORT_EXPORT_DIR}"
      GOBI_IMPORT_REPORT_MAIL_TO: "${GOBI_IMPORT_REPORT_MAIL_TO}"
      GOBI_IMPORT_ERROR_MAIL_TO: "${GOBI_IMPORT_ERROR_MAIL_TO}"
      GOBI_IMPORT_LOG_DIR: "${GOBI_IMPORT_LOG_DIR}"
      GOBI_IMPORT_LOG4PERL_CONF_FILE_PATH: "/opt/koha-gobi-import/log4perl.conf" # TODO: Relative path works?
      # Koha environment variables
      KOHA_CONF: "/etc/koha/sites/${KOHA_INSTANCE_NAME}/koha-conf.xml" #TODO: Move to dockerfile? Already have duplication of KOHA_USER, and KOHA_INSTANCE_NAME, would have to duplicate KOHA_INSTANCE_NAME in build .env
      DEBUG_MODE: 0
    cap_add:
     - SYS_NICE
     - DAC_READ_SEARCH
    depends_on:
      - mariadb
      - elasticsearch
      - rabbitmq
    volumes:
      - koha-plack-run:/run/koha-plack
  apache:
    image: docker.ub.gu.se/koha:${GIT_REVISION}
    entrypoint: ["/usr/local/bin/docker-entrypoint-apache.sh"]
    volumes:
      - koha-plack-run:/run/koha-plack
    ports:
      - "127.0.0.1:${KOHA_INTRANET_HOST_PORT}:8080"
      - "127.0.0.1:${KOHA_OPAC_HOST_PORT}:80"
  postgres:
    image: postgres:18.3
    environment:
      POSTGRES_USER: ${KOHA_PG_USER}
      POSTGRES_PASSWORD: ${KOHA_PG_PASS}
      POSTGRES_DB: ${KOHA_PG_DATABASE}
    volumes:
      - ./postgres-initdb.d:/docker-entrypoint-initdb.d:ro
      - "${POSTGRES_DATA_HOST_DIR}:/var/lib/postgresql/data"
  mariadb:
    image: mariadb:10.11-jammy
    environment:
      MARIADB_ROOT_PASSWORD: root_password
      MARIADB_USER: koha_koha
      MARIADB_PASSWORD: password
      MARIADB_DATABASE: koha_koha
    volumes:
      - ./mariadb-initdb.d:/docker-entrypoint-initdb.d:ro
      - "${MARIADB_DATA_HOST_DIR}:/var/lib/mysql"
  elasticsearch:
    image: docker.ub.gu.se/koha-elasticsearch:${ELASTICSEARCH_VERSION}
    environment:
      - xpack.security.enabled=false
      - "discovery.type=single-node"
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g" #TODO: Higher for production
    volumes:
      - "${ELASTICSEARCH_DATA_HOST_DIR}:/usr/share/elasticsearch/data"
  memcached:
    image: memcached:1.6
    command:
      - memcached
      - -m
      - 64m
  rabbitmq:
    image: docker.ub.gu.se/koha-rabbitmq:${RABBITMQ_VERSION}

volumes:
  koha-plack-run:
