---
all:
  hosts:
    kohalab:
      ansible_host: 89.45.233.21
      ansible_user: apps
      environment_name: lab
      koha_home: "/home/{{ ansible_user }}/koha-lab/current"
      koha_repo_version: release-2020.09-20210406.1551-cpanfix
      koha_po_files_path: "/home/{{ ansible_user }}/koha-lab/shared/misc/translator/po"
      koha_instance_name: koha
      koha_db_password: "{{ vault_koha_db_password }}"
      mariadb_root_password: "{{ vault_mariadb_root_password }}"
      gobi_report_mail_to: david.gustafsson@ub.gu.se,g.katalog@ub.gu.se
      gobi_error_mail_to: david.gustafsson@ub.gu.se,g.katalog@ub.gu.se,stefan.berndtsson@ub.gu.se
      koha_online_payment_portal_url: https://betala-staging.ub.gu.se/Koha/Payment
