---
environment_name: staging
intranet_server_name: "koha-staging-intra.ub.gu.se"
opac_server_name: "koha-staging.ub.gu.se"
koha_ipac_api_key: "{{ vault_koha_ipac_api_key }}"
get_print_data_api_key: "{{ vault_get_print_data_api_key }}"
koha_mojilicious_secret_passphrase: "{{ vault_koha_mojilicious_secret_passphrase }}"
koha_online_payment_portal_url: https://betala-staging.ub.gu.se/Koha/Payment

# Data dirs
data_dir: /mnt
