---
docker_command: './docker-compose-release.sh'
koha_environment: production
intranet_server_name: "koha-intra.ub.gu.se"
opac_server_name: "koha.ub.gu.se"
koha_instance_name: koha
gobi_report_mail_to: david.gustafsson@ub.gu.se,g.katalog@ub.gu.se
gobi_error_mail_to: david.gustafsson@ub.gu.se,g.katalog@ub.gu.se,stefan.berndtsson@ub.gu.se
koha_online_payment_portal_url: https://betala-production.ub.gu.se/Koha/Payment
# data dirs
data_dir: /mnt/data

# Mail settings #@TODO: FIX!!
smtp_host: 127.0.0.1
smtp_port: 25
smtp_username: ''
smtp_password: ''
smtp_ssl_mode: disabled
koha_database_backup_cron_enabled: true
gub_edifact_cron_enabled: true
edifact_cron_enabled: true
papercut_cron_enabled: true

# Edifact
edifact_email: gunda@ub.gu.se

edifact_dawson_user: "{{ vault_edifact_dawson_user }}"
edifact_dawson_password: "{{ vault_edifact_dawson_password }}"

edifact_delbanco_user: "{{ vault_edifact_delbanco_user }}"
edifact_delbanco_password: "{{ vault_edifact_delbanco_password }}"

edifact_adlibris_user: "{{ vault_edifact_adlibris_user }}"
edifact_adlibris_password: "{{ vault_edifact_adlibris_password }}"

edifact_bokus_user: "{{ vault_edifact_bokus_user }}"
edifact_bokus_password: "{{ vault_edifact_bokus_password }}"
